# Generated by Django 2.2.7 on 2020-05-02 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': '课程章节', 'verbose_name_plural': '课程章节'},
        ),
    ]
