# Generated by Django 2.2.7 on 2020-05-02 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_course_org'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_org',
        ),
    ]
